// Code generated by ogen, DO NOT EDIT.

package v1

// SecretmanagerVaultsDestroyParams is parameters of secretmanager_vaults_destroy operation.
type SecretmanagerVaultsDestroyParams struct {
	ResourceID string
}

// SecretmanagerVaultsRetrieveParams is parameters of secretmanager_vaults_retrieve operation.
type SecretmanagerVaultsRetrieveParams struct {
	ResourceID string
}

// SecretmanagerVaultsSecretsCreateParams is parameters of secretmanager_vaults_secrets_create operation.
type SecretmanagerVaultsSecretsCreateParams struct {
	VaultResourceID string
}

// SecretmanagerVaultsSecretsDestroyParams is parameters of secretmanager_vaults_secrets_destroy operation.
type SecretmanagerVaultsSecretsDestroyParams struct {
	VaultResourceID string
}

// SecretmanagerVaultsSecretsListParams is parameters of secretmanager_vaults_secrets_list operation.
type SecretmanagerVaultsSecretsListParams struct {
	VaultResourceID string
}

// SecretmanagerVaultsSecretsUnveilParams is parameters of secretmanager_vaults_secrets_unveil operation.
type SecretmanagerVaultsSecretsUnveilParams struct {
	VaultResourceID string
}

// SecretmanagerVaultsUpdateParams is parameters of secretmanager_vaults_update operation.
type SecretmanagerVaultsUpdateParams struct {
	ResourceID string
}
