// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"
	"net/url"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// SecretmanagerVaultsCreate invokes secretmanager_vaults_create operation.
	//
	// POST /secretmanager/vaults
	SecretmanagerVaultsCreate(ctx context.Context, request *WrappedCreateVault) (*WrappedCreateVault, error)
	// SecretmanagerVaultsDestroy invokes secretmanager_vaults_destroy operation.
	//
	// DELETE /secretmanager/vaults/{resource_id}
	SecretmanagerVaultsDestroy(ctx context.Context, params SecretmanagerVaultsDestroyParams) error
	// SecretmanagerVaultsList invokes secretmanager_vaults_list operation.
	//
	// GET /secretmanager/vaults
	SecretmanagerVaultsList(ctx context.Context) (*PaginatedVaultList, error)
	// SecretmanagerVaultsRetrieve invokes secretmanager_vaults_retrieve operation.
	//
	// GET /secretmanager/vaults/{resource_id}
	SecretmanagerVaultsRetrieve(ctx context.Context, params SecretmanagerVaultsRetrieveParams) (*WrappedVault, error)
	// SecretmanagerVaultsSecretsCreate invokes secretmanager_vaults_secrets_create operation.
	//
	// POST /secretmanager/vaults/{vault_resource_id}/secrets
	SecretmanagerVaultsSecretsCreate(ctx context.Context, request *WrappedCreateSecret, params SecretmanagerVaultsSecretsCreateParams) (*WrappedSecret, error)
	// SecretmanagerVaultsSecretsDestroy invokes secretmanager_vaults_secrets_destroy operation.
	//
	// DELETE /secretmanager/vaults/{vault_resource_id}/secrets
	SecretmanagerVaultsSecretsDestroy(ctx context.Context, request *WrappedDeleteSecret, params SecretmanagerVaultsSecretsDestroyParams) error
	// SecretmanagerVaultsSecretsList invokes secretmanager_vaults_secrets_list operation.
	//
	// GET /secretmanager/vaults/{vault_resource_id}/secrets
	SecretmanagerVaultsSecretsList(ctx context.Context, params SecretmanagerVaultsSecretsListParams) (*PaginatedSecretList, error)
	// SecretmanagerVaultsSecretsUnveil invokes secretmanager_vaults_secrets_unveil operation.
	//
	// POST /secretmanager/vaults/{vault_resource_id}/secrets/unveil
	SecretmanagerVaultsSecretsUnveil(ctx context.Context, request *WrappedUnveil, params SecretmanagerVaultsSecretsUnveilParams) (*WrappedUnveil, error)
	// SecretmanagerVaultsUpdate invokes secretmanager_vaults_update operation.
	//
	// PUT /secretmanager/vaults/{resource_id}
	SecretmanagerVaultsUpdate(ctx context.Context, request *WrappedVault, params SecretmanagerVaultsUpdateParams) (*WrappedVault, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	sec       SecuritySource
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, sec SecuritySource, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		sec:        sec,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// SecretmanagerVaultsCreate invokes secretmanager_vaults_create operation.
//
// POST /secretmanager/vaults
func (c *Client) SecretmanagerVaultsCreate(ctx context.Context, request *WrappedCreateVault) (*WrappedCreateVault, error) {
	res, err := c.sendSecretmanagerVaultsCreate(ctx, request)
	return res, err
}

func (c *Client) sendSecretmanagerVaultsCreate(ctx context.Context, request *WrappedCreateVault) (res *WrappedCreateVault, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/secretmanager/vaults"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSecretmanagerVaultsCreateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, SecretmanagerVaultsCreateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSecretmanagerVaultsCreateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SecretmanagerVaultsDestroy invokes secretmanager_vaults_destroy operation.
//
// DELETE /secretmanager/vaults/{resource_id}
func (c *Client) SecretmanagerVaultsDestroy(ctx context.Context, params SecretmanagerVaultsDestroyParams) error {
	_, err := c.sendSecretmanagerVaultsDestroy(ctx, params)
	return err
}

func (c *Client) sendSecretmanagerVaultsDestroy(ctx context.Context, params SecretmanagerVaultsDestroyParams) (res *SecretmanagerVaultsDestroyNoContent, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/secretmanager/vaults/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, SecretmanagerVaultsDestroyOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSecretmanagerVaultsDestroyResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SecretmanagerVaultsList invokes secretmanager_vaults_list operation.
//
// GET /secretmanager/vaults
func (c *Client) SecretmanagerVaultsList(ctx context.Context) (*PaginatedVaultList, error) {
	res, err := c.sendSecretmanagerVaultsList(ctx)
	return res, err
}

func (c *Client) sendSecretmanagerVaultsList(ctx context.Context) (res *PaginatedVaultList, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/secretmanager/vaults"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, SecretmanagerVaultsListOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSecretmanagerVaultsListResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SecretmanagerVaultsRetrieve invokes secretmanager_vaults_retrieve operation.
//
// GET /secretmanager/vaults/{resource_id}
func (c *Client) SecretmanagerVaultsRetrieve(ctx context.Context, params SecretmanagerVaultsRetrieveParams) (*WrappedVault, error) {
	res, err := c.sendSecretmanagerVaultsRetrieve(ctx, params)
	return res, err
}

func (c *Client) sendSecretmanagerVaultsRetrieve(ctx context.Context, params SecretmanagerVaultsRetrieveParams) (res *WrappedVault, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/secretmanager/vaults/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, SecretmanagerVaultsRetrieveOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSecretmanagerVaultsRetrieveResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SecretmanagerVaultsSecretsCreate invokes secretmanager_vaults_secrets_create operation.
//
// POST /secretmanager/vaults/{vault_resource_id}/secrets
func (c *Client) SecretmanagerVaultsSecretsCreate(ctx context.Context, request *WrappedCreateSecret, params SecretmanagerVaultsSecretsCreateParams) (*WrappedSecret, error) {
	res, err := c.sendSecretmanagerVaultsSecretsCreate(ctx, request, params)
	return res, err
}

func (c *Client) sendSecretmanagerVaultsSecretsCreate(ctx context.Context, request *WrappedCreateSecret, params SecretmanagerVaultsSecretsCreateParams) (res *WrappedSecret, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/secretmanager/vaults/"
	{
		// Encode "vault_resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "vault_resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.VaultResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/secrets"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSecretmanagerVaultsSecretsCreateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, SecretmanagerVaultsSecretsCreateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSecretmanagerVaultsSecretsCreateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SecretmanagerVaultsSecretsDestroy invokes secretmanager_vaults_secrets_destroy operation.
//
// DELETE /secretmanager/vaults/{vault_resource_id}/secrets
func (c *Client) SecretmanagerVaultsSecretsDestroy(ctx context.Context, request *WrappedDeleteSecret, params SecretmanagerVaultsSecretsDestroyParams) error {
	_, err := c.sendSecretmanagerVaultsSecretsDestroy(ctx, request, params)
	return err
}

func (c *Client) sendSecretmanagerVaultsSecretsDestroy(ctx context.Context, request *WrappedDeleteSecret, params SecretmanagerVaultsSecretsDestroyParams) (res *SecretmanagerVaultsSecretsDestroyNoContent, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/secretmanager/vaults/"
	{
		// Encode "vault_resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "vault_resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.VaultResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/secrets"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSecretmanagerVaultsSecretsDestroyRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, SecretmanagerVaultsSecretsDestroyOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSecretmanagerVaultsSecretsDestroyResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SecretmanagerVaultsSecretsList invokes secretmanager_vaults_secrets_list operation.
//
// GET /secretmanager/vaults/{vault_resource_id}/secrets
func (c *Client) SecretmanagerVaultsSecretsList(ctx context.Context, params SecretmanagerVaultsSecretsListParams) (*PaginatedSecretList, error) {
	res, err := c.sendSecretmanagerVaultsSecretsList(ctx, params)
	return res, err
}

func (c *Client) sendSecretmanagerVaultsSecretsList(ctx context.Context, params SecretmanagerVaultsSecretsListParams) (res *PaginatedSecretList, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/secretmanager/vaults/"
	{
		// Encode "vault_resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "vault_resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.VaultResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/secrets"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, SecretmanagerVaultsSecretsListOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSecretmanagerVaultsSecretsListResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SecretmanagerVaultsSecretsUnveil invokes secretmanager_vaults_secrets_unveil operation.
//
// POST /secretmanager/vaults/{vault_resource_id}/secrets/unveil
func (c *Client) SecretmanagerVaultsSecretsUnveil(ctx context.Context, request *WrappedUnveil, params SecretmanagerVaultsSecretsUnveilParams) (*WrappedUnveil, error) {
	res, err := c.sendSecretmanagerVaultsSecretsUnveil(ctx, request, params)
	return res, err
}

func (c *Client) sendSecretmanagerVaultsSecretsUnveil(ctx context.Context, request *WrappedUnveil, params SecretmanagerVaultsSecretsUnveilParams) (res *WrappedUnveil, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/secretmanager/vaults/"
	{
		// Encode "vault_resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "vault_resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.VaultResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/secrets/unveil"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSecretmanagerVaultsSecretsUnveilRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, SecretmanagerVaultsSecretsUnveilOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSecretmanagerVaultsSecretsUnveilResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SecretmanagerVaultsUpdate invokes secretmanager_vaults_update operation.
//
// PUT /secretmanager/vaults/{resource_id}
func (c *Client) SecretmanagerVaultsUpdate(ctx context.Context, request *WrappedVault, params SecretmanagerVaultsUpdateParams) (*WrappedVault, error) {
	res, err := c.sendSecretmanagerVaultsUpdate(ctx, request, params)
	return res, err
}

func (c *Client) sendSecretmanagerVaultsUpdate(ctx context.Context, request *WrappedVault, params SecretmanagerVaultsUpdateParams) (res *WrappedVault, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/secretmanager/vaults/"
	{
		// Encode "resource_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "resource_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ResourceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSecretmanagerVaultsUpdateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBasicAuth(ctx, SecretmanagerVaultsUpdateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BasicAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSecretmanagerVaultsUpdateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
