// Code generated by ogen, DO NOT EDIT.

package v1

// OperationName is the ogen operation name
type OperationName = string

const (
	SecretmanagerVaultsCreateOperation         OperationName = "SecretmanagerVaultsCreate"
	SecretmanagerVaultsDestroyOperation        OperationName = "SecretmanagerVaultsDestroy"
	SecretmanagerVaultsListOperation           OperationName = "SecretmanagerVaultsList"
	SecretmanagerVaultsRetrieveOperation       OperationName = "SecretmanagerVaultsRetrieve"
	SecretmanagerVaultsSecretsCreateOperation  OperationName = "SecretmanagerVaultsSecretsCreate"
	SecretmanagerVaultsSecretsDestroyOperation OperationName = "SecretmanagerVaultsSecretsDestroy"
	SecretmanagerVaultsSecretsListOperation    OperationName = "SecretmanagerVaultsSecretsList"
	SecretmanagerVaultsSecretsUnveilOperation  OperationName = "SecretmanagerVaultsSecretsUnveil"
	SecretmanagerVaultsUpdateOperation         OperationName = "SecretmanagerVaultsUpdate"
)
